name = "schoolwork-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "schoolwork-db"
database_id = "2002c64d-8115-484d-bc9a-85ca20b69611"

[[kv_namespaces]]
binding = "SESSIONS"
id = "72b83a3cd15747a3b4cee36a0f8f7324"

[durable_objects]
bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]

[[r2_buckets]]
binding = "FILES"
bucket_name = "schoolwork-files"

[vars]
FRONTEND_URL = "https://roentgenjon.github.io"
